learning_log/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),

]

learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'

urlpatterns = [
	path('', views.index, name='index'),
	path('topics/', views.topics, name='topics'),
	path('topics/<topic_id>/', views.topic, name='topic'),
	# Página para adicionar um novo assunto 
	path('new_topic/', views.new_topic, name='new_topic'),
	# Página para adicionar uma nova entrada 
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	# Para editar as entradas já existentes 
	path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),

	]

users/urls.py
"""Define padrões de URL para users."""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models

# Para deixar cada assunto e entrada com seus respectivos usuários 
from django.contrib.auth.models import User


class Topic(models.Model):
	text = models.CharField(max_length=200, verbose_name='assunto')
	date_added = models.DateTimeField(auto_now_add=True, verbose_name='Data')
	owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='autor')

	class Meta:
		verbose_name_plural = 'tópicos'

	def __str__(self):
		return self.text
		

class Entry(models.Model):
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name='tópico')
	text = models.TextField(verbose_name='comentários')
	date_added = models.DateTimeField(auto_now_add=True, verbose_name='data')

	class Meta:
		verbose_name_plural = 'entradas'

	def __str__(self):
		return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from  .models import Topic, Entry


class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''} 



# classe que eu digite, NAO FUNCONOU

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': 'Entrada'} # nao tinha func., não tinha posto chaves.
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
# from django.shortcuts import render, redirect
# # from django.http import HttpResponseRedirect
# # from django.urls import reverse
# from .models import Topic, Entry
# from .forms import TopicForm, EntryForm


from django.shortcuts import render, redirect

from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404


def index(request):
	return render(request, 'learning_logs/index.html')
	
@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
	"""adiciona um novo assunto."""
	if request.method != 'POST':
		# Nenhum dado submetido; cria um formulário em branco 
		form = TopicForm()
	else:
		# Dados do POST submetidos; processa os Dados
		form = TopicForm(request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return redirect('learning_logs:topics')

	# formulário em branco ou inválido 
	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
	"""Acrescenta uma nova entrada para um assunto em particular."""
	topic = Topic.objects.get(id=topic_id)

	if request.method != 'POST':
		# Nenhum dado submetido; cria um formulário em branco 
		form = EntryForm()
	else:
		# Dados de POST submetidos; processa os Dados
		form = EntryForm(data=request.POST)
		if form.is_valid:
			new_entry = form.save(commit=False)
			new_entry.topic = topic 
			new_entry.save()
			return redirect('learning_logs:topic', topic_id=topic_id)

	context = {'topic': topic, 'form': form}
	return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)









	

users/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.   
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('learning_logs:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Miniblog</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
        Home</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:topics'%}">
              Tópicos</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text"}">Olá, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Sair</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Criar conta</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Logar</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
  
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>
	<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
</p>

	<p>Editar entrada:</p>

	<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button nane="submit">Salvar</button>
		
	</form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<div class="jumbotron"> 
<h1 class="display-3">Miniblog do Eliel.</h1>
	<p>
		Este mini-blog foi criado com intuito de organizar os estudos de Python, Django, programação em geral...ou, ainda, qualquer tema que tenha relevância geral.
	</p>
	
	<p>Este miniblog foi criado com a ajuda do livro <strong>Curso Intensivo de Python</strong> de Eric Matthes.</p>

	<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
		role="button">Registrar &raquo; </a>

</div>




{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

	<p>Adicionar nova entrada:</p>
	<form action="{% url 'learning_logs:new_entry' topic.id %}" 
	 method="post">
	 	{% csrf_token %}
	 	{{ form.as_p }}
	 	<button name="submit">adicionar entrada</button>
	</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

	<p> Adicionar novo tópico:</p>

	<form action="{% url 'learning_logs:new_topic' %}" method="post" >
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Adicionar</button>	
	</form>
		
{% endblock content %}		

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
	<h3>{{ topic }}</h3>
  
{% endblock page_header %}


{% block content %}


	
	<p>
		
		<a href="{% url 'learning_logs:new_entry' topic.id %}"> Adicionar nova entrada</a>
	</p>

	<ul>
	{% for entry in entries %}
		<div class="card mb-3">
		<h4 class="card-header">
			{{ entry.date_added|date:'d/m/y H:i' }}
			<small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
				editar entrada</a></small>
		</h4>
		<div class="card-body">
			{{ entry.text|linebreaks }}
		</div>
		</div>
	{% empty %}
		<p>Não há nenhum comentário sobre este assunto ainda.</p>
	{% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Tópicos</h1>
{% endblock page_header %}

{% block content %}

	
	<ul>
		{% for topic in topics %}
			<li> <h3>
				<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
			</h3></li>
		{% empty %}

			<li><h3> Nenhum tópico adicionado ainda.</h3></li>
		{% endfor %}
	</ul>

	<h3><a href="{% url 'learning_logs:new_topic' %}">Novo tópico:</a></h3>

{% endblock content %}